#!/bin/sh
while :
do
	#prompt for mode
	dialog --menu "RCX Flash Tool" 10 30 3 1 flash\ full\ firmware 2 write\ programs\ only 3 shutdown\ system 2>m_temp

	#OK
	if [ "$?" = "0" ]
	then
		_classcount=0
		_classlist=""
		for D in $(dirname $0)/../classes/*; do
			if [ -d "${D}" ];
			then
				_classcount=$(($_classcount+1))
				_classlist="$_classlist $_classcount $(basename ${D})"
			fi
		done
		#echo $_classlist
		#sleep 5

		_flashmode=$(cat m_temp)
		rm -f m_temp
		
		#Shutdown selected
		if [ "$_flashmode" = "3" ]
		then
			sync
			sudo shutdown -h now
			sleep 5
			break
		fi

		dialog --menu "Choose program to load..." 10 30 3 $_classlist 2>d_temp

		if [ "$?" = "0" ]
		then
			_flashdir=$(dirname $0)/../classes/$(echo $_classlist | sed 's/.*\([^0-9]\|^\)'"$(cat d_temp)"'\ \([^ ]*\)\(\ \|$\).*/\2/')
			rm -f d_temp

			#full firmware flash
			if [ "$_flashmode" = "1" ]
			then
				echo $_flashdir
				_lastcmd="$(dirname $0)/flash-rcx-class $_flashdir"
				$(dirname $0)/flash-rcx-class $_flashdir
				sleep 5
				while :
				do
					dialog --yesno "Program another brick with the same settings?" 10 30
					if [ "$?" = "1" ]
					then
						break
					fi
					$_lastcmd
					sleep 5
				done
			fi

			#program only flash
			if [ "$_flashmode" = "2" ]
			then
				_lastcmd="$(dirname $0)/flash-rcx-class -s $_flashdir"
				$(dirname $0)/flash-rcx-class -s $_flashdir
				sleep 5
				while :
				do
					dialog --yesno "Program another brick with the same settings?" 10 30
					if [ "$?" = "1" ]
					then
						break
					fi
					$_lastcmd
					sleep 5
				done
			fi
		fi

	else
		echo "User Canceled"
		rm -f m_temp
		rm -f d_temp
		break
	fi
done


#s/.*\([^0-9]\|^\)5\ \([^ ]*\)\(\ \|$\).*/\2/
